// const fs = require("fs");
// // console.log("Hello");
// // console.log(jsonObject);

// // create a JSON object
// const user = {
//   id: 1,
//   name: "John Doe",
//   age: 22,
// };

// // convert JSON object to string
// const data = JSON.stringify(user);

// // write JSON string to a file
// fs.writeFile("user.json", data, (err) => {
//   if (err) {
//     throw err;
//   }
//   console.log("JSON data is saved.");
// });

const data = {
  "gkanishk@live.com": { firstName: "Kanishk", lastName: "Gupta" },
  "suyashpradhan07@gmail.com": { firstName: "Suyash", lastName: "Pradhan" },
  "mohammedsadiq6531@gmail.com": {
    firstName: "Mohammed ",
    lastName: "Sadiq M",
  },
  "parimal.najan@gmail.com": { firstName: "Parimal ", lastName: "Najan" },
  "shashankorthiwada@gmail.com": {
    firstName: "Shashank",
    lastName: "Korthiwada",
  },
  "vineetsinghal2312@gmail.com": { firstName: "Vineet ", lastName: "Singhal" },
  "nrusinghamohanty9182@gmail.com": {
    firstName: "Nrusingha ",
    lastName: "Mohanty",
  },
  "asohail737@gmail.com": { firstName: "Sohail ", lastName: "Ansari" },
  "kpwat66@gmail.com": { firstName: "Karthik ", lastName: "Prabhu" },
  "Gs816912@gmail.com": { firstName: "Gagandeep", lastName: "Singh" },
  "adevade16@gmail.com": { firstName: "Anagha ", lastName: "Devade" },
  "sahiljaiswal1398@gmail.com": { firstName: "Sahil ", lastName: "Jaiswal" },
  "nadaaofficial19@gmail.com": { firstName: "Nada ", lastName: "Farook" },
  "saswatidas279@gmail.com": { firstName: "Saswati ", lastName: "Das" },
  "diha19cs@cmrit.ac.in": { firstName: "Disha ", lastName: "Hati" },
  "hhrshmistry@gmail.com": { firstName: "Harsh ", lastName: "Mistry" },
  "iamshubambhasin@gmail.com": { firstName: "Shubam ", lastName: "Bhasin" },
  "ashishshetty2612@gmail.com": { firstName: "Ashish", lastName: "J Shetty" },
  "prashantdev4u@gmail.com": { firstName: "Prashant Dev ", lastName: "Singh" },
  "sudeshkumardas7@gmail.com": { firstName: "Sudesh kumar ", lastName: "das" },
  "shaikhamaan257@gmail.com": { firstName: "Amaan ", lastName: "Shaikh" },
  "asmitshrivastava8@gmail.com": {
    firstName: "Asmit ",
    lastName: "shrivastava",
  },
  "tarkjot1998kaur@gmail.com": { firstName: "Tarkjot ", lastName: "Kaur" },
  "tamrakardivyansh189@gmail.com": {
    firstName: "Divyansh ",
    lastName: "Tamrakar",
  },
  "shushmagowda22@gmail.com": { firstName: "Shushma ", lastName: "M" },
  "adityanair102001@gmail.com": {
    firstName: "ADITYA ",
    lastName: "MANOJ NAIR",
  },
  "hiralalppurohit@gmail.com": { firstName: "Hiralal ", lastName: "Purohit" },
  "tausifaman222@gmail.com": { firstName: "SYED ", lastName: "TAUSIF AHMED" },
  "jinathyasmin123@gmail.com": {
    firstName: "Jinath ",
    lastName: "Yasmin Laskar",
  },
  "arifjamal2012@gmail.com": { firstName: "Arif ", lastName: "Jamal" },
  "melvinfernando175@gmail.com": { firstName: "Melvin ", lastName: "Fernando" },
  "rohiraanjali@gmail.com": { firstName: "Anjali ", lastName: "Rohira" },
  "ayush.ak5555@gmail.com": { firstName: "Ayush ", lastName: "Kumar" },
  "snehaupujari@gmail.com": { firstName: "Sneha ", lastName: "Pujari" },
  "ptjimmy99@gmail.com": { firstName: "Jugal ", lastName: "K Patel" },
  "joygupta501@gmail.com": { firstName: "Joy ", lastName: "Gupta" },
  "sarathdon9245@gmail.com": { firstName: "Sarathkumar", lastName: ".U" },
  "sakshijjain1997@gmail.com": { firstName: "Sakshi ", lastName: "Jain" },
  "sendtosupriya@gmail.com": {
    firstName: "Supriya ",
    lastName: "Minnasandram",
  },
  "varenaggarwal@gmail.com": { firstName: "Varen ", lastName: "Aggarwal" },
  "radhika7002@gmail.com": { firstName: "Radhika ", lastName: "Joshi" },
  "harshithece7016@gmail.com": {
    firstName: "Harshith ",
    lastName: "Venkatesh",
  },
  "utsavkumar280@gmail.com": { firstName: "Utsav ", lastName: "Kumar" },
  "pruthvirajmv.code@gmail.com": { firstName: "Pruthviraj ", lastName: "M V" },
  "manali.bagale@gmail.com": { firstName: "Ankita ", lastName: "Bagale" },
  "pradhanbrati@gmail.com": { firstName: "Brati ", lastName: "Pradhan" },
  "rajmanish6851@gmail.com": { firstName: "Manish ", lastName: "Raj" },
  "himanshumaheshraj0786@gmail.com": {
    firstName: "Himanshu ",
    lastName: "Sachan",
  },
  "mehta.rashita18@gmail.com": { firstName: "Rashita" },
  "karthikrcr9@gmail.com": { firstName: "Sai ", lastName: "Karthik P" },
  "payal.kherajani19@gmail.com": { firstName: "Payal ", lastName: "Kherajani" },
  "gauravggg21@gmail.com": { firstName: "Gaurav ", lastName: "Agarwal" },
  "harshitsaxena586@gmail.com": { firstName: "Harshit ", lastName: "Saxena" },
  "achalsaharan999@gmail.com": { firstName: "Achal ", lastName: "Saharan" },
  "gauravstajanpure@gmail.com": { firstName: "Gaurav ", lastName: "Tajanpure" },
  "rushichaudhari1237@gmail.com": {
    firstName: "Rushikesh ",
    lastName: "Chaudhari",
  },
  "porwalharshp@gmail.com": { firstName: "Harsh ", lastName: "Porwal" },
  "vermashivam527@gmail.com": { firstName: "Shivam ", lastName: "Verma" },
  "jatinranka123@gmail.com": { firstName: "Jatin ", lastName: "G" },
  "priyampoddar89@gmail.com": { firstName: "PRIYAM ", lastName: "PODDAR" },
  "ashish08rewa@gmail.com": { firstName: "Ashish ", lastName: "Gupta" },
  "aruntiwary009@gmail.com": { firstName: "Arun ", lastName: "Tiwary" },
  "adarshpandya0@gmail.com": { firstName: "Adarsh ", lastName: "Pandya" },
  "piyushbisht1997@gmail.com": { firstName: "Piyush ", lastName: "Bisht" },
  "yogeshkasliwal707@gmail.com": {
    firstName: "Yogesh ",
    lastName: "Mahavir Kasliwal",
  },
  "akshay.nighthawk@gmail.com": {
    firstName: "Akshay ",
    lastName: "Laxmipathi",
  },
  "masumtycoon@gmail.com": { firstName: "Masum ", lastName: "Ahmed Choudhuri" },
  "vedant.karia@somaiya.edu": { firstName: "Vedant ", lastName: "Karia" },
  "mdsaayim@gmail.com": { firstName: "Mohammed ", lastName: "Saayim" },
  "bvijaysandilya@gmail.com": { firstName: "Vijay ", lastName: "Sandilya" },
  "sabharwalpragya@gmail.com": { firstName: "pragya ", lastName: "sabarwal" },
  "srishtisinha12996@gmail.com": { firstName: "Srishti ", lastName: "Sinha" },
  "shasheesh.purohit15@gmail.com": {
    firstName: "Shasheesh",
    lastName: "Purohit",
  },
  "rdhatrak19@gmail.com": { firstName: "Rohit ", lastName: "Dhatrak" },
  "kinshukshah@gmail.com": { firstName: "Kinshuk ", lastName: "Shah" },
  "prerananw1@gmail.com": { firstName: "Prerana ", lastName: "Suhas Nawar" },
  "deepakyadav2672@gmail.com": { firstName: "Deepak ", lastName: "Yadav" },
  "harshitbadolla5@gmail.com": { firstName: "Harshit ", lastName: "M" },
  "ayush20892@gmail.com": { firstName: "Ayush ", lastName: "Sharma" },
  "punithmilano@gmail.com": { firstName: "Punith ", lastName: "Kumar" },
  "ankitknag@gmail.com": { firstName: "Ankit ", lastName: "K Nag" },
  "guptadivyanshu2012@gmail.com": {
    firstName: "Divyanshu ",
    lastName: "Gupta",
  },
  "prynsu@yahoo.com": { firstName: "Priyanshu" },
  "dheerajmalikwork@gmail.com": { firstName: "Dheeraj ", lastName: "Malik" },
  "sohamshah456@gmail.com": { firstName: "Soham ", lastName: "Shah" },
  "borudeomkar41@gmail.com": { firstName: "Omkar ", lastName: "Borude" },
  "saisumanthkacham@gmail.com": {
    firstName: "kacham ",
    lastName: "sai sumanth",
  },
  "stutiprasad63@gmail.com": { firstName: "Stuti ", lastName: "Prasad" },
  "tiwariaditya1579@gmail.com": { firstName: "Aditya ", lastName: "R Tiwari" },
  "kuldeeprathore74@gmail.com": { firstName: "kuldeep ", lastName: "singh" },
  "rishabhkunwar11@gmail.com": { firstName: "Rishabh ", lastName: "Kunwar" },
  "amithakur081@gmail.com": { firstName: "Amit ", lastName: "Thakur" },
  "rahulr1116@gmail.com": { firstName: "Rahul ", lastName: "Ravindran" },
  "jineshsonawat9929@gmail.com": { firstName: "Jinesh ", lastName: "Sonawat" },
  "amanpandey340@gmail.com": { firstName: "Aman ", lastName: "Pandey" },
  "waraa.vignesh@gmail.com": {
    firstName: "Vigneshwaraa ",
    lastName: "Sarangapani",
  },
  "shobhit1727@gmail.com": { firstName: "Shobhit ", lastName: "Kuruvilla" },
  "vaishnavchandurkar12@gmail.com": {
    firstName: "Vaishnav ",
    lastName: "A. Chandurkar",
  },
  "tonnyvijayan@gmail.com": { firstName: "Tonny ", lastName: "Vijayan" },
  "aamyear@gmail.com": { firstName: "Aamir ", lastName: "Mazhar Abbas" },
  "amansethi221306@gmail.com": { firstName: "Aman ", lastName: "Sethi" },
  "guptayush0022@gmail.com": { firstName: "Ayush ", lastName: "Gupta" },
  "shailesh.dev296@gmail.com": { firstName: "Shailesh ", lastName: "pandey" },
  "maiprakashkumar@gmail.com": { firstName: "Prakash ", lastName: "Kumar" },
  "sainitheesh002@gmail.com": { firstName: "SAINITHEESH ", lastName: "ERRA" },
  "pidarraman@gmail.com": { firstName: "Raman ", lastName: "Pidar" },
  "kunaltijare77@gmail.com": {
    firstName: "Kunal ",
    lastName: "Keshaorao Tijare",
  },
  "harshitbharani786@gmail.com": { firstName: "Harshit ", lastName: "Bharani" },
  "anugusaitejareddy@outlook.com": {
    firstName: "SaiTeja ",
    lastName: "Reddy Anugu",
  },
  "hritikjain707@gmail.com": { firstName: "Atishay ", lastName: "Jain" },
  "ramac6662@gmail.com": { firstName: "Rama ", lastName: "Chandran" },
  "narangnitesh@ymail.com": { firstName: "Nitesh ", lastName: "Narang" },
  "lalitmendha102@gmail.com": {
    firstName: "Lalit ",
    lastName: "Kishor Mendha",
  },
  "shraddha.jain3219@gmail.com": { firstName: "S Shraddha", lastName: "Jain" },
  "mansiagarwal451@gmail.com": { firstName: "Mansi ", lastName: "Agarwal" },
  "harshdeshpande100@gmail.com": { firstName: "Harsh ", lastName: "Deshpande" },
  "sajagagarwal0402@gmail.com": { firstName: "Sajag ", lastName: "Agarwal" },
  "mahatoroshan1999@gmail.com": {
    firstName: "Roshan ",
    lastName: "Kumar Mahato",
  },
  "arnavraj22.official@gmail.com": { firstName: "Arnav", lastName: "Raj" },
  "chandanamj325@gmail.com": { firstName: "Chandana", lastName: "Mahajan" },
  "shilpaaggarwal3495@gmail.com": { firstName: "Shilpa", lastName: "aggarwal" },
  "renukapaturkar1998@gmail.com": {
    firstName: "Renuka ",
    lastName: "Paturkar",
  },
  "prajvalhl@gmail.com": { firstName: "Prajval ", lastName: "H L" },
  "ruchika1997.rs@gmail.com": { firstName: "Ruchika ", lastName: "Srivastava" },
  "amitrs852852@gmail.com": { firstName: "Amit ", lastName: "Rakesh Mishra" },
  "siddharthlodha42@gmail.com": { firstName: "Siddharth", lastName: "Lodha" },
  "sharmasaurabh2412@gmail.com": { firstName: "Saurabh ", lastName: "sharma" },
  "mailme.tuhindas@gmail.com": { firstName: "Tuhin ", lastName: "Das" },
  "bulsaraharshil@gmail.com": { firstName: "Harshil ", lastName: "Bulsara" },
  "joyanserrao@gmail.com": { firstName: "Joyan ", lastName: "serrao" },
  "prakhar.10.varshney@gmail.com": {
    firstName: "Prakhar ",
    lastName: "Varshney",
  },
  "2607varsha@gmail.com": { firstName: "Varsha ", lastName: "H N" },
  "jaysingh20196@gmail.com": { firstName: "Jay ", lastName: "singh dhakad" },
  "omkarak45@gmail.com": { firstName: "Omkar ", lastName: "Kulkarni" },
  "avinesh49@gmail.com": { firstName: "Avinesh", lastName: "P" },
  "mdshahazaduddin@gmail.com": { firstName: "MD SHAHAZAD ", lastName: "UDDIN" },
  "tejp2nd@gmail.com": { firstName: "Tej ", lastName: "Patel" },
  "tarunpro0710@gmail.com": { firstName: "Tarun ", lastName: "Lal Rajak" },
  "hranaritsh@gmail.com": { firstName: "Himanshu ", lastName: "Rana" },
  "vineeth.thaviti@gmail.com": {
    firstName: "Thaviti. Pavan Vineeth ",
    lastName: "Reddy",
  },
  "sachin0196@gmail.com": { firstName: "Sachin ", lastName: "Pant" },
  "hpro373@gmail.com": { firstName: "Pratim Kumar ", lastName: "Hazarika" },
  "Sahithisiripuram1001@gmail.com": {
    firstName: "Sahithi ",
    lastName: "Siripuram",
  },
  "ganeshgajula22@gmail.com": { firstName: "Ganesh ", lastName: "Gajula" },
  "rajmishra0125@gmail.com": { firstName: "Raj ", lastName: "Mishra" },
  "99singhpuneet99@gmail.com": {
    firstName: "Puneet",
    lastName: "Ranvijay Singh",
  },
  "akashpre196@gmail.com": { firstName: "AKASH KUMAR ", lastName: "SINGH" },
  "andleebsyed75@gmail.com": {
    firstName: "Syed Andleeb ",
    lastName: "Ul Islam",
  },
  "rkjain119@gmail.com": { firstName: "RUSHAB KUMAR ", lastName: "JAIN" },
  "prithvisuvarna56@gmail.com": {
    firstName: "Prithviraj ",
    lastName: "Suvarna",
  },
  "vermarishi1203@gmail.com": { firstName: "Rishi ", lastName: "Verma" },
  "prkantikar69@gmail.com": { firstName: "Premsai ", lastName: "Kantikar" },
  "mehta2155@outlook.com": { firstName: "Sandeep ", lastName: "Mehta" },
  "Jyotipal1323@gmail.com": { firstName: "Jyoti", lastName: "pal" },
  "hntejas@gmail.com": { firstName: "Tejas ", lastName: "H N" },
  "shubhamghuge34@gmail.com": {
    firstName: "shubham ",
    lastName: "subhash ghuge",
  },
  "mankkaju@gmail.com": { firstName: "Kajol ", lastName: "Sharma" },
  "poonammohata2@gmail.com": { firstName: "Poonam ", lastName: "Mohata" },
  "vinu6th@gmail.com": { firstName: "Vignesh ", lastName: "B S" },
  "rohang9896@gmail.com": { firstName: "Rohan ", lastName: "Gupta" },
  "pranamhegde3@gmail.com": { firstName: "Pranam ", lastName: "Hegde" },
  "omkarkolate8@gmail.com": { firstName: "Omkar ", lastName: "Kolate" },
  "akashgajwar@gmail.com": { firstName: "Akash ", lastName: "Gajwar" },
  "madhushree.kunder.05@gmail.com": {
    firstName: "Madhushree",
    lastName: "Kunder",
  },
  "nitinmalave14@gmail.com": { firstName: "Nitin ", lastName: "Malave" },
  "gokulg1412@gmail.com": { firstName: "Gokul ", lastName: "Gopi" },
  "themohammadsa@gmail.com": { firstName: "Mohammad S A" },
  "kushanksriraj@gmail.com": { firstName: "Kushank ", lastName: "Sriraj" },
  "vishrawat510@gmail.com": { firstName: "Vishal ", lastName: "Rawat" },
  "suprio.roy94@gmail.com": { firstName: "Suprio ", lastName: "Roy" },
  "biswassaurav71@gmail.com": { firstName: "Saurav ", lastName: "Biswas" },
  "pranjalmahajan96@gmail.com": { firstName: "Pranjal ", lastName: "Mahajan" },
  "janakishreeja23@gmail.com": { firstName: "Janaki ", lastName: "Shreeja" },
  "minakshimittalm3@gmail.com": { firstName: "Minakshi ", lastName: "Mittal" },
  "madhusudan707@gmail.com": { firstName: "MADHUSUDAN ", lastName: "DAS" },
  "amarjitsingh99225@gmail.com": {
    firstName: "Amarjit ",
    lastName: "Sinder Singh",
  },
  "atameshwari9@gmail.com": { firstName: "Atul ", lastName: "Tameshwari" },
  "mohdbilal16@gmail.com": { firstName: "Bilal", lastName: "Mohammad" },
  "msahu300@gmail.com": { firstName: "Manish ", lastName: "Kumar Sahu" },
  "sourabhmahato5701@gmail.com": { firstName: "sourabh ", lastName: "mahato" },
  "shshankm597@gmail.com": {
    firstName: "Shashank ",
    lastName: "Shekhar Mishra",
  },
  "kumara2048@gmail.com": { firstName: "Kumaraswamy A" },
  "akashmehrotra29@gmail.com": { firstName: "Akash ", lastName: "Mehrotra" },
  "surajbg07@gmail.com": { firstName: "Suraj ", lastName: "BG" },
  "ameyjoshi2001rj@gmail.com": { firstName: "Amey ", lastName: "Joshi" },
  "kishanmandora13@gmail.com": { firstName: "Kishan ", lastName: "Mandora" },
  "syed.minhaj0911@gmail.com": {
    firstName: "SYED MINHAH ",
    lastName: "HUSSAIN",
  },
  "aroraomkar@gmail.com": { firstName: "Omkar ", lastName: "Arora" },
  "ankushpndt@gmail.com": { firstName: "Ankush ", lastName: "Sharma" },
  "manu.mandalreddy@gmail.com": {
    firstName: "Mandalreddy ",
    lastName: "Manasa",
  },
  "sruthiragupathy@gmail.com": { firstName: "Sruthi R" },
  "ayanshukla4@gmail.com": { firstName: "Ayan ", lastName: "Shukla" },
  "kshivam99.create@gmail.com": { firstName: "Shivam", lastName: "Kumar" },
  "chaudharimehul2001@gmail.com": {
    firstName: "Mehul",
    lastName: "Kiran Chaudhari",
  },
  "vaibhavsingh5520@gmail.com": {
    firstName: "SIngh Vaibhavkumar ",
    lastName: "Ambuj",
  },
  "parabsoham01@gmail.com": { firstName: "Soham ", lastName: "Parab" },
  "wadher32@gmail.com": { firstName: "Virendra Bipin ", lastName: "Wadher" },
  "rahulrajnkeht@gmail.com": { firstName: "Rahul ", lastName: "Kumar" },
  "007sumanghosh@gmail.com": { firstName: "SUMAN ", lastName: "GHOSH" },
  "jainlokesh318@gmail.com": { firstName: "Lokesh ", lastName: "Jain" },
  "robinhooda66@gmail.com": { firstName: "Robin ", lastName: "Hooda" },
  "apurvchimralwar1997@gmail.com": {
    firstName: "Apurv ",
    lastName: "Chimralwar",
  },
  "sayurikamble123@gmail.com": { firstName: "Sayuri ", lastName: "Kamble" },
  "sneha.amruth24@gmail.com": { firstName: "Sneha ", lastName: "Amruth" },
  "khusharth19@gmail.com": { firstName: "Khusharth ", lastName: "A. Patani" },
  "arun.syriac@outlook.com": { firstName: "Arun ", lastName: "Syriac" },
  "ajit.v.billava@gmail.com": {
    firstName: "Ajith ",
    lastName: "Vishwanatha Billava",
  },
  "g.jaynil2401@gmail.com": { firstName: "Jaynil ", lastName: "Atul Gaglani" },
  "vrampranav9@gmail.com": { firstName: "Rampranav ", lastName: "Vadlamani" },
  "vinaybajjuri58@gmail.com": { firstName: "Vinay Kumar", lastName: "Bajjuri" },
  "sunny.panguluri@gmail.com": {
    firstName: "Bhanu Teja ",
    lastName: "Panguluri",
  },
  "jainprajwal123@gmail.com": {
    firstName: "Prajwal ",
    lastName: "Vishal Jain",
  },
  "gogawat31@gmail.com": { firstName: "Ankit ", lastName: "Singh Gogawat" },
  "souvikjana2013@gmail.com": { firstName: "Souvik ", lastName: "Jana" },
  "yogpendse2000@gmail.com": { firstName: "Yogesh ", lastName: "Pendse" },
  "nishankt139@outlook.com": {
    firstName: "Nishank ",
    lastName: "Madanpal Tembhurne",
  },
  "vikasvk1997@gmail.com": { firstName: "Vikas ", lastName: "V K" },
  "sohelkhan0378@gmail.com": { firstName: "Mohammad Sohel ", lastName: "Khan" },
  "aravindanravi33@gmail.com": { firstName: "Aravindan ", lastName: "Ravi" },
  "aneenajohn@gmail.com": { firstName: "Aneena John ", lastName: "Xavier" },
  "sneha.adlakha@gmail.com": { firstName: "Sneha ", lastName: "Adlakha" },
  "papasaniraviteja@gmail.com": {
    firstName: "Ravi Teja ",
    lastName: "Papasani",
  },
  "manmodesanket@gmail.com": { firstName: "Sanket ", lastName: "Manmode" },
  "kanishkgupta1234@gmail.com": { firstName: "Kanishk ", lastName: "Gupta" },
  "neharajesh1997@gmail.com": { firstName: "Neha ", lastName: "Rajesh" },
  "ritikadhimanritz@gmail.com": { firstName: "Ritika ", lastName: "Dhiman" },
  "rshvbharti@gmail.com": { firstName: "Rishav ", lastName: "Bharti" },
  "ahmeddanish111@gmail.com": { firstName: "Danish ", lastName: "Ahmed" },
  "siddharthvikram.svs96@gmail.com": {
    firstName: "Siddharth",
    lastName: "Vikram",
  },
  "pooja.sabnani93@gmail.com": {
    firstName: "Pooja ",
    lastName: "Vasudev Sabnani",
  },
  "kunal8011@gmail.com": { firstName: "Kunal ", lastName: "Gupta" },
  "sarthakchaudhary52@gmail.com": { firstName: "Sarthak ", lastName: "Lav" },
  "rkrk44321@gmail.com": { firstName: "Radha ", lastName: "Krishnan .R" },
  "purammohankumar@gmail.com": { firstName: "Puram Mohan ", lastName: "Kumar" },
  "rupamdas832@gmail.com": { firstName: "RUPAM ", lastName: "DAS" },
  "satvikchachra19@gmail.com": { firstName: "Satvik ", lastName: "Chachra" },
  "muthu101kumaran@gmail.com": { firstName: "Muthu ", lastName: "Kumaran" },
  "sparsh2823@gmail.com": { firstName: "Sparsh ", lastName: "Singh Rathore" },
  "priyagupta314@gmail.com": { firstName: "Priya ", lastName: "Gupta" },
  "surabhiadak8@gmail.com": { firstName: "Surabhi ", lastName: "Adak" },
  "iamrakeshkumar@pm.me": { firstName: "Rakesh ", lastName: "Kumar" },
  "codetastic101@gmail.com": { firstName: "Sushil ", lastName: "Buragute" },
  "akshitasaini007@gmail.com": { firstName: "Akshita ", lastName: "Saini" },
  "vishal1982c@gmail.com": { firstName: "CHET VISHAL ", lastName: "TUNJU" },
  "akshayrajput103@gmail.com": { firstName: "Akshay ", lastName: "Rajput" },
  "dhruvarora9931@gmail.com": { firstName: "Dhruv ", lastName: "arora" },
  "hellreet46@gmail.com": { firstName: "Reet", lastName: "Srivastava" },
  "knackofabhinav@gmail.com": { firstName: "Abhinav" },
  "akhilmovva@gmail.com": { firstName: "Akhil ", lastName: "Movva" },
  "gauravdey625@gmail.com": { firstName: "Gourav Kumar ", lastName: "Dey" },
  "deepalikundwani4@gmail.com": { firstName: "Deepali ", lastName: "Kundwani" },
  "sarthak242@gmail.com": { firstName: "Sarthak" },
  "priyansh.maurya@gmail.com": { firstName: "Priyansh ", lastName: "Maurya" },
  "arora.veshu@gmail.com": { firstName: "Vikrant ", lastName: "Arora" },
  "yashkoolwal2018@gmail.com": { firstName: "Yash ", lastName: "Koolwal" },
  "varunipandey32@gmail.com": { firstName: "Varuni ", lastName: "Pandey" },
  "advaithunni2000@gmail.com": { firstName: "Advaith ", lastName: "U" },
  "shettydhruvesh16@gmail.com": { firstName: "dhruvesh ", lastName: "shetty" },
  "meetlukka10@gmail.com": { firstName: "Meet ", lastName: "Dilipbhai Lukka" },
  "hetav.desai20@gmail.com": { firstName: "Hetav ", lastName: "Desai" },
  "aditya.agrawal0309@gmail.com": { firstName: "Aditya ", lastName: "Agrawal" },
  "amydharap@gmail.com": { firstName: "AMRUTA ", lastName: "D" },
  "arpan19991025@gmail.com": { firstName: "ARPAN ", lastName: "MONDAL" },
  "khanujabhupinder09@gmail.com": {
    firstName: "Bhupinder ",
    lastName: "Singh",
  },
  "pdiresh@gmail.com": { firstName: "Diresh ", lastName: "Kumar Pradhan" },
  "naveen.kamath002@gmail.com": { firstName: "Naveen ", lastName: "Kamath" },
  "nikhilpd791@gmail.com": { firstName: "Nikhil ", lastName: "Prasad" },
  "pfulsundar8@gmail.com": {
    firstName: "Pranita ",
    lastName: "Ramdas Fulsundar",
  },
  "pranshu.dobhal@gmail.com": { firstName: "Pranshu ", lastName: "Dobhal" },
  "rajsyeola@gmail.com": { firstName: "RAJ BHAGWANT ", lastName: "YEOLA" },
  "rawheat.gulati@hotmail.com": { firstName: "Rohit ", lastName: "Gulati" },
  "ruchiupadhyay281292@gmail.com": {
    firstName: "Ruchi ",
    lastName: "Upadhyay",
  },
  "choubeysanskar03@gmail.com": { firstName: "Sanskar ", lastName: "Choubey" },
  "saurabhkamboj1997@gmail.com": { firstName: "Saurabh", lastName: "kambhoj" },
  "shashikantkalshetty1605@gmail.com": {
    firstName: "shashikant ",
    lastName: "kallshetty",
  },
  "shivanshagrawal1997@gmail.com": {
    firstName: "Shivaansh ",
    lastName: "Agarwal",
  },
  "utpalpati8@gmail.com": { firstName: "Utpal ", lastName: "Pati" },
  "ishanjirety24@gmail.com": { firstName: "Ishan ", lastName: "jirety" },
  "ashwin.khode1@gmail.com": { firstName: "Ashwin ", lastName: "Khode" },
  "nair.akshay98@gmail.com": { firstName: "Akshay ", lastName: "S R" },
  "sakshambhatt33@gmail.com": { firstName: "Saksham ", lastName: "Bhatt" },
  "vaibhavdesai888@gmail.com": {
    firstName: "Vaibhav",
    lastName: "Suryakant Desai",
  },
  "maxsaurav237@gmail.com": { firstName: "Saurav ", lastName: "Kumar" },
  "upadhayayshivam06@gmail.com": { firstName: "shivam ", lastName: "upadhyay" },
  "ankit.karn.ak@gmail.com": { firstName: "Ankit ", lastName: "Karn" },
  "nirav.kyada.9@gmail.com": { firstName: "Nirav ", lastName: "Kyada" },
  "shaikhvms@gmail.com": { firstName: "Vasim ", lastName: "Usman Shaikh" },
  "srividyamvenkatesh@gmail.com": {
    firstName: "Srividya ",
    lastName: "Mysore Venkatesh",
  },
  "panchamitulupule97@gmail.com": {
    firstName: "Panchami ",
    lastName: "Thulupule",
  },
  "purvashet@gmail.com": { firstName: "Purva ", lastName: "Jitendra Sheth" },
  "vidsagrawal1812@gmail.com": { firstName: "Vidushi ", lastName: "Agrawal" },
  "mukulsaini176@gmail.com": { firstName: "Mukul ", lastName: "Saini" },
  "uditkumarussa@gmail.com": { firstName: "Udit ", lastName: "Kumar" },
  "sagar.dhamani1@gmail.com": { firstName: "Sagar ", lastName: "Dhamani" },
  "piyushsingh0992@gmail.com": { firstName: "Piyush ", lastName: "singh" },
  "rajputjay901@gmail.com": { firstName: "Jay ", lastName: "Rajput" },
  "ankit.singhania767@gmail.com": {
    firstName: "Ankit ",
    lastName: "Singhania",
  },
  "shubhamsng7@gmail.com": { firstName: "Shubham ", lastName: "Singh" },
  "mvganeshk15sde@gmail.com": { firstName: "M.V.Ganesh ", lastName: "Kumar" },
  "kartikeydwivedipara@gmail.com": {
    firstName: "Kartikey ",
    lastName: "Dwivedi",
  },
  "sr@shahidrizwan.com": { firstName: "Mohammed ", lastName: "Shahid Rizwan" },
  "rupeshgupta369@gmail.com": {
    firstName: "Rupesh ",
    lastName: "Lalman Gupta",
  },
  "alishvagadiya2202@gmail.com": { firstName: "Alish ", lastName: "Vagadiya" },
  "singhadi672@gmail.com": { firstName: "Aditya ", lastName: "Singh" },
  "ashrayparmar0307@gmail.com": { firstName: "Ashray ", lastName: "Parmar" },
  "gs8280601@gmail.com": { firstName: "Gaurav Kumar ", lastName: "Sharma" },
  "anshuldaksh2016@gmail.com": {
    firstName: "Anshul ",
    lastName: "Daksh Prajapati",
  },
  "connect.bhavesh.kasturi@gmail.com": {
    firstName: "Bhavesh ",
    lastName: "Kasturi",
  },
  "ajinkyajagdale21@gmail.com": {
    firstName: "Ajinkya",
    lastName: "H Jagadale",
  },
  "manan228@gmail.com": { firstName: "Manan", lastName: "Shah" },
  "rb.rishibhosale@gmail.com": {
    firstName: "SHUBHAM ",
    lastName: "VINAYAK BHOSALE",
  },
  "vishalch181@gmail.com": { firstName: "Vishal ", lastName: "Chaudhary" },
  "chetansdhangar@gmail.com": {
    firstName: "Chetan ",
    lastName: "Sunil Dhangar",
  },
};

console.log(Object.keys(data).length);
